# Generated by Django 6.0.3 on 2026-03-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_initial'),
        ('properties', '0001_initial'),
        ('tenancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tenancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenancies.tenancy'),
        ),
        migrations.AddField(
            model_name='payment',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transaction', to='payments.payment'),
        ),
    ]
