# Generated by Django 6.0.3 on 2026-03-19 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_day', models.PositiveSmallIntegerField(default=5)),
                ('fine_type', models.CharField(choices=[('flat', 'Flat Fee'), ('percentage', 'Percentage'), ('per_day', 'Per Day'), ('percentage_per_day', 'Percentage Per Day'), ('none', 'No Fine')], default='none', max_length=30)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fine_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_charges', models.JSONField(blank=True, default=list)),
                ('water_bill', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('garbage_bill', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('security_levy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custom_charges', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('apartment', 'Apartment Block'), ('bungalow_complex', 'Bungalow Complex'), ('townhouse_complex', 'Townhouse Complex'), ('mixed_use', 'Mixed Use'), ('commercial', 'Commercial Building'), ('standalone', 'Standalone House')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('county', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('lease_agreement', 'Lease Agreement'), ('tenancy', 'Tenancy'), ('other', 'Other')], default='other', max_length=40)),
                ('file', models.FileField(upload_to='property_documents/%Y/%m/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('floor', models.IntegerField(default=1)),
                ('unit_type', models.CharField(choices=[('bedsitter', 'Bedsitter'), ('studio', 'Studio'), ('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom'), ('4_bedroom', '4 Bedroom'), ('penthouse', 'Penthouse'), ('bungalow', 'Bungalow'), ('townhouse', 'Townhouse'), ('villa', 'Villa'), ('shop', 'Shop / Commercial')], max_length=30)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
