# Generated by Django 6.0.3 on 2026-03-19 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending_signature', 'Pending Signature'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='pending_signature', max_length=30)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='lease_documents/%Y/%m/')),
                ('termination_reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
