# Generated by Django 6.0.3 on 2026-03-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leases', '0002_initial'),
        ('properties', '0001_initial'),
        ('tenancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='tenancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='tenancies.tenancy'),
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='properties.unit'),
        ),
    ]
